SELECT * FROM guma; 
--구매자 아이디(ID), 상품 개수(P_NUMBER), 상품 고유 번호(P_CODE);

SELECT * FROM user_infomation; 
--구매자 아이디(ID), 출생 연도(DATE_OF_BIRTHDAY), 성별(GENDER);

-- 10대 여성 아이디
SELECT ID
FROM user_infomation
WHERE GENDER = 'F' AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATE_OF_BIRTHDAY) BETWEEN 10 AND 19;

-- 20대 여성 아이디
SELECT ID
FROM user_infomation
WHERE GENDER = 'F' AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATE_OF_BIRTHDAY) BETWEEN 20 AND 29;

-- 30대 이상 여성 아이디
SELECT ID
FROM user_infomation
WHERE GENDER = 'F' AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATE_OF_BIRTHDAY) >= 30;

-- 10대 남성 아이디
SELECT ID
FROM user_infomation
WHERE GENDER = 'M' AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATE_OF_BIRTHDAY) BETWEEN 10 AND 19;

-- 20대 남성 아이디
SELECT ID
FROM user_infomation
WHERE GENDER = 'M' AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATE_OF_BIRTHDAY) BETWEEN 20 AND 29;

-- 30대 이상 남성 아이디
SELECT ID
FROM user_infomation
WHERE GENDER = 'M' AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATE_OF_BIRTHDAY) >= 30;

-- 10대 여성이 많이 구매한 상품 코드
SELECT *
FROM (
SELECT P_CODE, SUM(P_NUMBER) AS TOTAL_PURCHASE
FROM guma
WHERE ID IN (
SELECT ID
FROM user_infomation
WHERE GENDER = 'F' AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATE_OF_BIRTHDAY) BETWEEN 10 AND 19
)
GROUP BY P_CODE
ORDER BY TOTAL_PURCHASE DESC
)
WHERE ROWNUM <= 8;

-- 20대 여성이 많이 구매한 상품 코드
SELECT *
FROM (
SELECT P_CODE, SUM(P_NUMBER) AS TOTAL_PURCHASE
FROM guma
WHERE ID IN (
SELECT ID
FROM user_infomation
WHERE GENDER = 'F' AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATE_OF_BIRTHDAY) BETWEEN 20 AND 29
)
GROUP BY P_CODE
ORDER BY TOTAL_PURCHASE DESC
)
WHERE ROWNUM <= 8;

-- 30대 이상 여성이 많이 구매한 상품 코드
SELECT *
FROM (
SELECT P_CODE, SUM(P_NUMBER) AS TOTAL_PURCHASE
FROM guma
WHERE ID IN (
SELECT ID
FROM user_infomation
WHERE GENDER = 'F' AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATE_OF_BIRTHDAY) >= 30
)
GROUP BY P_CODE
ORDER BY TOTAL_PURCHASE DESC
)
WHERE ROWNUM <= 8;

-- 10대 남성이 많이 구매한 상품 코드
SELECT *
FROM (
SELECT P_CODE, SUM(P_NUMBER) AS TOTAL_PURCHASE
FROM guma
WHERE ID IN (
SELECT ID
FROM user_infomation
WHERE GENDER = 'M' AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATE_OF_BIRTHDAY) BETWEEN 10 AND 19
)
GROUP BY P_CODE
ORDER BY TOTAL_PURCHASE DESC
)
WHERE ROWNUM <= 8;

-- 20대 남성이 많이 구매한 상품 코드
SELECT *
FROM (
SELECT P_CODE, SUM(P_NUMBER) AS TOTAL_PURCHASE
FROM guma
WHERE ID IN (
SELECT ID
FROM user_infomation
WHERE GENDER = 'M' AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATE_OF_BIRTHDAY) BETWEEN 20 AND 29
)
GROUP BY P_CODE
ORDER BY TOTAL_PURCHASE DESC
)
WHERE ROWNUM <= 8;

-- 30대 이상 남성이 많이 구매한 상품 코드
SELECT *
FROM (
SELECT P_CODE, SUM(P_NUMBER) AS TOTAL_PURCHASE
FROM guma
WHERE ID IN (
SELECT ID
FROM user_infomation
WHERE GENDER = 'M' AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATE_OF_BIRTHDAY) >= 30
)
GROUP BY P_CODE
ORDER BY TOTAL_PURCHASE DESC
)
WHERE ROWNUM <= 8;










