






SELECT * FROM guma; 
--구매자 아이디(ID), 상품 개수(OR_NUM), 상품 고유 번호(PR_KEY);

SELECT * FROM member; 
--구매자 아이디(ID), 출생 연도(DATE_BIRTHDAY), 성별(GENDER);

SELECT * FROM product;
--URL(PR_THUMBNAIL), 상품 고유번호(PR_KEY)

SELECT * FROM product;
-- PR_KEY(상품 코드), PR_NAME(상품 이름), PR_PRICE(원래 가격), PR_DCPRICE(할인가), PR_DCPER(할인율)

-- 10대 여성 아이디
SELECT ID
FROM member
WHERE GENDER = 'F' AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATE_BIRTHDAY) BETWEEN 10 AND 19;

-- 20대 여성 아이디
SELECT ID
FROM member
WHERE GENDER = 'F' AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATE_BIRTHDAY) BETWEEN 20 AND 29;

-- 30대 이상 여성 아이디
SELECT ID
FROM member
WHERE GENDER = 'F' AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATE_BIRTHDAY) >= 30;

-- 10대 남성 아이디
SELECT ID
FROM member
WHERE GENDER = 'M' AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATE_BIRTHDAY) BETWEEN 10 AND 19;

-- 20대 남성 아이디
SELECT ID
FROM member
WHERE GENDER = 'M' AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATE_BIRTHDAY) BETWEEN 20 AND 29;

-- 30대 이상 남성 아이디
SELECT ID
FROM member
WHERE GENDER = 'M' AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM DATE_BIRTHDAY) >= 30;

-- 10대 여성이 많이 구매한 상품 코드
SELECT t.PR_THUMBNAIL, g.PR_KEY, p.PR_NAME, p.PR_PRICE, p.PR_DCPRICE, p.PR_DCPER
FROM (
  SELECT m.id, t.or_pr_count, t.pr_key
  FROM member m, orders o, or_detail t
  WHERE m.id = o.id and o.or_key = t.or_key and PR_KEY IN (
    SELECT PR_KEY
    FROM product
  )
) g
JOIN member u ON g.ID = u.ID
JOIN product t ON g.PR_KEY = t.PR_KEY
JOIN product p ON g.PR_KEY = p.PR_KEY
WHERE u.GENDER = 'F'
  AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.DATE_BIRTHDAY) BETWEEN 10 AND 19
  AND ROWNUM <= 8
GROUP BY t.PR_THUMBNAIL, g.PR_KEY, p.PR_NAME, p.PR_PRICE, p.PR_DCPRICE, p.PR_DCPER
ORDER BY COUNT(*) DESC;


-- 20대 여성이 많이 구매한 상품 코드
-- 20대 여성이 많이 구매한 상품 코드
SELECT t.PR_THUMBNAIL, g.PR_KEY, p.PR_NAME, p.PR_PRICE, p.PR_DCPRICE, p.PR_DCPER
FROM (
SELECT *
FROM guma
WHERE PR_KEY IN (
SELECT PR_KEY
FROM product
)
) g, member u, product t, product p
WHERE g.ID = u.ID
AND g.PR_KEY = t.PR_KEY
AND g.PR_KEY = p.PR_KEY
AND u.GENDER = 'F'
AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.DATE_BIRTHDAY) BETWEEN 20 AND 29
AND ROWNUM <= 8
GROUP BY t.PR_THUMBNAIL, g.PR_KEY, p.PR_NAME, p.PR_PRICE, p.PR_DCPRICE, p.PR_DCPER
ORDER BY COUNT(*) DESC;

-- 30대 이상 여성이 많이 구매한 상품 코드
SELECT t.PR_THUMBNAIL, g.PR_KEY, p.PR_NAME, p.PR_PRICE, p.PR_DCPRICE, p.PR_DCPER
FROM (
SELECT *
FROM guma
WHERE PR_KEY IN (
SELECT PR_KEY
FROM product
)
) g, member u, product t, product p
WHERE g.ID = u.ID
AND g.PR_KEY = t.PR_KEY
AND g.PR_KEY = p.PR_KEY
AND u.GENDER = 'F'
AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.DATE_BIRTHDAY) >= 30
AND ROWNUM <= 8
GROUP BY t.PR_THUMBNAIL, g.PR_KEY, p.PR_NAME, p.PR_PRICE, p.PR_DCPRICE, p.PR_DCPER
ORDER BY COUNT(*) DESC;

-- 10대 남성이 많이 구매한 상품 코드
SELECT t.PR_THUMBNAIL, g.PR_KEY, p.PR_NAME, p.PR_PRICE, p.PR_DCPRICE, p.PR_DCPER
FROM (
SELECT *
FROM guma
WHERE PR_KEY IN (
SELECT PR_KEY
FROM product
)
) g, member u, product t, product p
WHERE g.ID = u.ID
AND g.PR_KEY = t.PR_KEY
AND g.PR_KEY = p.PR_KEY
AND u.GENDER = 'M'
AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.DATE_BIRTHDAY) BETWEEN 10 AND 19
AND ROWNUM <= 8
GROUP BY t.PR_THUMBNAIL, g.PR_KEY, p.PR_NAME, p.PR_PRICE, p.PR_DCPRICE, p.PR_DCPER
ORDER BY COUNT(*) DESC;

-- 20대 남성이 많이 구매한 상품 코드
SELECT t.PR_THUMBNAIL, g.PR_KEY, p.PR_NAME, p.PR_PRICE, p.PR_DCPRICE, p.PR_DCPER
FROM (
  SELECT *
  FROM guma
  WHERE PR_KEY IN (
    SELECT PR_KEY
    FROM product
  )
) g
INNER JOIN member u ON g.ID = u.ID
INNER JOIN product t ON g.PR_KEY = t.PR_KEY
INNER JOIN product p ON g.PR_KEY = p.PR_KEY
WHERE u.GENDER = 'M'
  AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.DATE_BIRTHDAY) BETWEEN 20 AND 29
  AND ROWNUM <= 8
GROUP BY t.PR_THUMBNAIL, g.PR_KEY, p.PR_NAME, p.PR_PRICE, p.PR_DCPRICE, p.PR_DCPER
ORDER BY COUNT(*) DESC;

-- 30대 이상 남성이 많이 구매한 상품 코드
SELECT t.PR_THUMBNAIL, g.PR_KEY, p.PR_NAME, p.PR_PRICE, p.PR_DCPRICE, p.PR_DCPER
FROM (
  SELECT *
  FROM guma
  WHERE PR_KEY IN (
    SELECT PR_KEY
    FROM product
  )
) g
INNER JOIN member u ON g.ID = u.ID
INNER JOIN product t ON g.PR_KEY = t.PR_KEY
INNER JOIN product p ON g.PR_KEY = p.PR_KEY
WHERE u.GENDER = 'M'
  AND EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM u.DATE_BIRTHDAY) >= 30
  AND ROWNUM <= 8
GROUP BY t.PR_THUMBNAIL, g.PR_KEY, p.PR_NAME, p.PR_PRICE, p.PR_DCPRICE, p.PR_DCPER
ORDER BY COUNT(*) DESC;



pr_dcper(할인율)
pr_dcperice(할인가)
pr_price(가격)








